config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#home'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  localized do
    get 'home' => 'pages#home'
    get 'dashboard' => 'pages#dashboard'
    get 'contact' => 'contacts#new'
    post 'contact' => 'contacts#create'

    resources :maintenances, concerns: :paginatable
    resources :mileages, concerns: :paginatable
    resources :cars, except: %i[show index]

    resources :reminders, concerns: :paginatable do
      member do
        get 'archive'
        get 'restore_archived'
      end

      get 'archived', on: :collection
    end
  end

  post 'requests/user_position'

  namespace :admin do
    root 'regular_users#index'

    resources :regular_users
    resources :admin_users
    resources :cars
    resources :reminders
    resources :maintenances
    resources :workshops
    resources :mileages
  end

  localized do
    devise_for :users
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/reminder.rb
# frozen_string_literal: true

class Reminder < ApplicationRecord
  include MostRecentable
  extend FriendlyId

  friendly_id :name, use: :slugged

  acts_as_paranoid

  belongs_to :car

  validates :name, presence: true

  scope :order_table, -> { order('sended DESC NULLS LAST', reminder_date: :desc) }
  scope :archived, -> { where.not(archived: nil) }
  scope :not_archived, -> { where(archived: nil) }
end

app/controllers/admin/reminders_controller.rb
# frozen_string_literal: true

module Admin
  class RemindersController < Admin::ApplicationController
    # Define a custom finder by overriding the `find_resource` method:
    def find_resource(param)
      Reminder.friendly.find(param)
    end
  end
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  before_action :find_reminder, only: %i[show edit update destroy archive restore_archived]

  def index
    @reminders = current_user.reminders.not_archived.order_table.page params[:page]
    @archive = false
  end

  def archived
    @reminders = current_user.reminders.archived.order_table.page params[:page]
    @archive = true
    render :index
  end

  def new
    @reminder = Reminder.new
  end

  def create
    @reminder = Reminder.new(reminder_params)

    if @reminder.save
      redirect_to reminders_path, notice: t('message_of_addition')
    else
      render :new
    end
  end

  def update
    if @reminder.update(reminder_params)
      redirect_to reminders_path, notice: t('message_of_modification')
    else
      render :edit
    end
  end

  def destroy
    @reminder.destroy
    redirect_to reminders_path, notice: t('message_of_deletion')
  end

  def archive
    if @reminder.update(archived: Date.today)
      redirect_to reminders_path, notice: t('.message_about_archiving')
    else
      flash[:danger] = t('.message_about_archiving_fail')
    end
  end

  def restore_archived
    if @reminder.update(archived: nil)
      redirect_to reminders_path, notice: t('.message_about_restoring')
    else
      flash[:danger] = t('.message_about_restoring_fail')
    end
  end

  private

  def reminder_params
    params.require(:reminder).permit(%i[name reminder_date mileage note car_id sended archived])
  end

  def find_reminder
    @reminder = current_user.reminders.friendly.find(params[:id])
  end
end

app/views/reminders/_form.html.haml
= simple_form_for @reminder do |f|
  = f.input :name, as: :string
  = f.input :mileage, as: :integer
  = f.input :reminder_date, as: :string,
    input_html: { class: 'datepicker', value: l_date(f.object.reminder_date) }
  = f.input :note, as: :text
  = f.association :car, collection: current_user.cars.decorate,
    label_method: :name, prompt: t('choose_option')
  = f.button :submit
  = link_to t('back'), :back, class: 'btn btn-secondary'

app/views/reminders/_reminder.html.haml
%tr{ class: ('table-secondary' if reminder.sended.present?) }
  %td= link_to reminder.name, reminder
  %td= reminder.car.decorate.name
  %td= reminder.decorate.mileage
  %td= l_date reminder.reminder_date
  - if @archive
    %td= link_to t('.restore'), restore_archived_reminder_path(reminder)
  - else
    %td= link_to t('edit'), edit_reminder_path(reminder)
    %td= link_to t('destroy'), reminder, method: :delete, data: { confirm: t('are_you_sure') }
    %td= link_to t('.archive_now'), archive_reminder_path(reminder)

app/views/reminders/edit.html.haml
= render 'form'

app/views/reminders/index.html.haml
= link_to t('add_new'), new_reminder_path(@reminder), class: 'btn btn-success'
= link_to t('.current'), reminders_path, class: 'btn btn-secondary'
= link_to t('.archive'), archived_reminders_path, class: 'btn btn-secondary'

.autopagerize_page_element
  %table.table.table-hover.mt-3
    %thead
      %tr
        %th{ scope: 'col' }= Reminder.model_name.human
        %th{ scope: 'col' }= Car.model_name.human
        %th{ scope: 'col' }= Reminder.human_attribute_name(:mileage)
        %th{ scope: 'col' }= Reminder.human_attribute_name(:reminder_date)
        %th{ scope: 'col', colspan: (@archive ? 1 : 3) }

      = render @reminders

= paginate @reminders

app/views/reminders/new.html.haml
= render 'form'

app/views/reminders/show.html.haml
%p
  %strong= Reminder.human_attribute_name(:name)
  = @reminder.name

%p
  %strong= Car.model_name.human
  = @reminder.car.decorate.name

%p
  %strong= Reminder.human_attribute_name(:reminder_date)
  = l_date(@reminder.reminder_date)
%p
  %strong= Reminder.human_attribute_name(:mileage)
  = @reminder.decorate.mileage

%p
  %strong= Reminder.human_attribute_name(:note)
  = @reminder.note

= link_to t('destroy'),
  @reminder, method: :delete, data: { confirm: t('are_you_sure') },
  class: 'btn btn-danger'

= link_to t('edit'), edit_reminder_path(@reminder), class: 'btn btn-success'
= link_to t('back'), reminders_path, class: 'btn btn-secondary'