config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#home'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  localized do
    get 'home' => 'pages#home'
    get 'dashboard' => 'pages#dashboard'
    get 'contact' => 'contacts#new'
    post 'contact' => 'contacts#create'

    resources :maintenances, concerns: :paginatable
    resources :mileages, concerns: :paginatable
    resources :cars, except: %i[show index]

    resources :reminders, concerns: :paginatable do
      member do
        get 'archive'
        get 'restore_archived'
      end

      get 'archived', on: :collection
    end
  end

  post 'requests/user_position'

  namespace :admin do
    root 'regular_users#index'

    resources :regular_users
    resources :admin_users
    resources :cars
    resources :reminders
    resources :maintenances
    resources :workshops
    resources :mileages
  end

  localized do
    devise_for :users
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/dashboard_blocks/_cars.html.haml
%p.card-text
  %table.table
    %thead
      %tr
        %th{ scope: 'col' }= Car.model_name.human
        %th
        %th
          =  link_to new_car_path, class: 'btn btn-success btn-sm text-white' do
            = content_tag(:i, nil, class: 'fa fa-plus')
            = t('add')

    %tbody
      - data[:cars].each do |car|
        %tr
          %td= car.name
          %td
            = link_to car,
            method: :delete,
            data: { confirm: t('are_you_sure') },
            class: 'btn btn-secondary btn-sm text-white' do
              = content_tag(:i, nil, class: 'fa fa-times')
              = t('destroy')
          %td
            = link_to edit_car_path(car), class: 'btn btn-secondary btn-sm text-white' do
              = content_tag(:i, nil, class: 'fa fa-pencil')
              = t('edit')

app/views/pages/dashboard_blocks/_closest_service.html.haml
.text-center
  %button.btn.btn-primary.mb-1{ onclick: 'Dashboard.setLocation()' }
    = t('.update_location')
  %p #{t('.last_known_position')}: #{data[:closest_service][:address]}
#position-info
.carousel.slide#carousel-example-controls{ 'data-ride' => 'carousel',
'data-interval' => '7000' }
  .carousel-inner
    - data[:closest_service][:places].keys.each_with_index do |type_of_place, index|
      .carousel-item{ class: index.zero? ? 'active' : nil }
        .service-box
          %h5= t(".#{type_of_place}")
          - if data[:closest_service][:places][type_of_place].empty?
            %h6= t('.not_found')
          %table.table.table-hover
            %tbody
              - data[:closest_service][:places][type_of_place].first(2).each do |service|
                %tr
                  %td
                    = link_to service[:name], google_place_url(service), target: :blank
                    .adress-font= service[:vicinity]

  %a.carousel-control-prev{ 'data-slide' => 'prev',
  :href => '#carousel-example-controls', :role => 'button' }
    %span.carousel-control-prev-icon{ 'aria-hidden' => 'true' }
    %span.sr-only Previous
  %a.carousel-control-next{ 'data-slide' => 'next',
  :href => '#carousel-example-controls', :role => 'button' }
    %span.carousel-control-next-icon{ 'aria-hidden' => 'true' }
    %span.sr-only Next

app/views/pages/dashboard_blocks/_closest_service_init.html.haml
.text-center
  %button{ onclick: 'Dashboard.setLocation()' }
    = t('.set_location')
  #position-info

app/views/pages/dashboard_blocks/_maintenance.html.haml
%p.card-text
  %h5 #{t('.last_added')} (#{ link_to t('all'), maintenances_path})

  %table.table.table-sm
    %thead
      %tr
        %th{ scope: 'col' }= Maintenance.model_name.human
        %th{ scope: 'col' }= Car.model_name.human
    %tbody
      - data[:maintenances].each do |maintenance|
        %tr
          %td= link_to maintenance.name, maintenance
          %td= maintenance.car.decorate.name

app/views/pages/dashboard_blocks/_mileage.html.haml
%p.card-text
  %h5 #{t('.last_added')} (#{ link_to t('all'), mileages_path})

  %table.table.table-sm
    %thead
      %tr
        %th{ scope: 'col' }= Car.model_name.human
        %th{ scope: 'col' }= Mileage.model_name.human
        %th{ scope: 'col' }= Mileage.human_attribute_name('date')
    %tbody
      - data[:mileages].each do |mileage|
        %tr
          %td= mileage.car.decorate.name
          %td= link_to mileage.meter_status, mileage
          %td= l_date mileage.date

app/views/pages/dashboard_blocks/_reminders.html.haml
%p.card-text
  %h5 #{t('.last_added')} (#{link_to t('all'), reminders_path})

  %table.table.table-sm
    %thead
      %tr
        %th{ scope: 'col' }= Reminder.model_name.human
        %th{ scope: 'col' }= Car.model_name.human
    %tbody
      - data[:reminders].each do |reminder|
        %tr
          %td= link_to reminder.name, reminder
          %td= reminder.car.decorate.name
