config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#home'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  localized do
    get 'home' => 'pages#home'
    get 'dashboard' => 'pages#dashboard'
    get 'contact' => 'contacts#new'
    post 'contact' => 'contacts#create'

    resources :maintenances, concerns: :paginatable
    resources :mileages, concerns: :paginatable
    resources :cars, except: %i[show index]

    resources :reminders, concerns: :paginatable do
      member do
        get 'archive'
        get 'restore_archived'
      end

      get 'archived', on: :collection
    end
  end

  post 'requests/user_position'

  namespace :admin do
    root 'regular_users#index'

    resources :regular_users
    resources :admin_users
    resources :cars
    resources :reminders
    resources :maintenances
    resources :workshops
    resources :mileages
  end

  localized do
    devise_for :users
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/mileage.rb
# frozen_string_literal: true

class Mileage < ApplicationRecord
  include MostRecentable

  acts_as_paranoid

  belongs_to :car

  validates :meter_status, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :date, presence: true
end

app/controllers/admin/mileages_controller.rb
# frozen_string_literal: true

module Admin
  class MileagesController < Admin::ApplicationController
  end
end

app/controllers/mileages_controller.rb
# frozen_string_literal: true

class MileagesController < ApplicationController
  before_action :find_mileage, only: %i[show edit update destroy]

  def index
    @mileages = current_user.mileages.page params[:page]
  end

  def new
    @mileage = Mileage.new
  end

  def create
    @mileage = Mileage.new(mileage_params)

    if @mileage.save
      redirect_to mileages_path, notice: t('message_of_addition')
    else
      render :new
    end
  end

  def update
    if @mileage.update(mileage_params)
      redirect_to mileages_path, notice: t('message_of_modification')
    else
      render :edit
    end
  end

  def destroy
    message = @mileage.destroy ? 'message_of_deletion' : 'message_of_deletion_fail'
    redirect_to mileages_path, notice: I18n.t(message)
  end

  private

  def mileage_params
    params.require(:mileage).permit(:meter_status, :car_id, :date)
  end

  def find_mileage
    @mileage = current_user.mileages.find(params[:id])
  end
end

app/views/mileages/_form.html.haml
= simple_form_for @mileage do |f|
  = f.input :meter_status, as: :integer
  = f.association :car,
    collection: current_user.cars.decorate,
    label_method: :name, prompt: t('choose_option')

  = f.input :date, as: :string, input_html: { class: 'datepicker', value: l_date(f.object.date) }
  = f.button :submit
  = link_to t('back'), :back, class: 'btn btn-secondary'

app/views/mileages/_mileage.html.haml
%tr
  %td= mileage.car.decorate.name
  %td= link_to mileage.meter_status, mileage
  %td= l_date mileage.date
  %td= link_to t('edit'), edit_mileage_path(mileage)
  %td= link_to t('destroy'), mileage, method: :delete, data: { confirm: t('are_you_sure') }

app/views/mileages/edit.html.haml
= render 'form'

app/views/mileages/index.html.haml
= link_to t('add_new'), new_mileage_path(@mileage), class: 'btn btn-primary'

.autopagerize_page_element
  %table.table.table-hover.mt-3
    %thead
      %tr
        %th{ scope: 'col' }= Car.model_name.human
        %th{ scope: 'col' }= Mileage.human_attribute_name :meter_status
        %th{ scope: 'col' }= Mileage.human_attribute_name :date
        %th{ scope: 'col', colspan: '2' }

    %tbody
      = render @mileages

= paginate @mileages

app/views/mileages/show.html.haml
%p
  %strong #{Car.model_name.human}:
  = @mileage.car.decorate.name
%p
  %strong #{Mileage.human_attribute_name :meter_status}:
  = @mileage.meter_status
%p
  %strong #{Mileage.human_attribute_name :date}:
  = l_date(@mileage.date)

= link_to t('destroy'),
  @mileage, method: :delete, data: { confirm: t('are_you_sure') },
  class: 'btn btn-danger'

= link_to t('edit'), edit_mileage_path(@mileage), class: 'btn btn-success'
= link_to t('back'), mileages_path, class: 'btn btn-secondary'