config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#home'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  localized do
    get 'home' => 'pages#home'
    get 'dashboard' => 'pages#dashboard'
    get 'contact' => 'contacts#new'
    post 'contact' => 'contacts#create'

    resources :maintenances, concerns: :paginatable
    resources :mileages, concerns: :paginatable
    resources :cars, except: %i[show index]

    resources :reminders, concerns: :paginatable do
      member do
        get 'archive'
        get 'restore_archived'
      end

      get 'archived', on: :collection
    end
  end

  post 'requests/user_position'

  namespace :admin do
    root 'regular_users#index'

    resources :regular_users
    resources :admin_users
    resources :cars
    resources :reminders
    resources :maintenances
    resources :workshops
    resources :mileages
  end

  localized do
    devise_for :users
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_class_for(type)} alert-dismissible fade show", role: 'alert' }
    %button.close{ 'data-dismiss' => 'alert', type: 'button' }
      %span{ 'aria-hidden' => 'true' } ×
    %strong
      = message

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %span.text-muted &copy; Workshop-team 2017 -  #{Time.current.year}

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  %button.navbar-toggler.navbar-toggler-right{ 'aria-controls' => 'navbar-supported-content',
  'aria-expanded' => 'false',
  'aria-label' => 'Toggle navigation',
  'data-target' => '#navbar-supported-content',
  'data-toggle' => 'collapse',
  type: 'button' }
    %span.navbar-toggler-icon
  %a.navbar-brand{ href: root_path } MOTOHELPER
  .collapse.navbar-collapse#navbar-supported-content
    %ul.navbar-nav.mr-auto
      %li.nav-item
        - if user_signed_in? && current_user.admin?
          = link_to t('.admin'), admin_root_path, class: 'nav-link'
      %li.nav-item
        = link_to t('.dashboard'), dashboard_path, class: 'nav-link'
      %li.nav-item
        = link_to t('.contact'), contact_path, class: 'nav-link'
    %ul.navbar-nav.my-2.my-lg-0
      - if user_signed_in?
        .dropdown.show
          %a.btn.btn-secondary.dropdown-toggle#dropdown-menu-link{ 'aria-expanded' => 'false',
          'aria-haspopup' => 'true',
          'data-toggle' => 'dropdown',
          href: '#', role: 'button' }
            = image_tag current_user.avatar.url(:thumb), class: 'header-avatar'
            = current_user.name
          .dropdown-menu.dropdown-menu-left{ 'aria-labelledby' => 'dropdown-menu-link' }
            = link_to t('.edit_profile'), edit_user_registration_path, class: 'dropdown-item'
            = link_to t('.logout'),
              destroy_user_session_path,
              method: :delete, class: 'dropdown-item'
      - else
        %li.nav-item
          = link_to t('.login'), new_user_session_path, class: 'nav-link'
        %li.nav-item
          = link_to t('.register'), new_user_registration_path, class: 'nav-link'

app/views/layouts/_header_administrate.html.haml
.administrate-menu
  = link_to 'Home', root_path
  |
  = link_to('Logout', destroy_user_session_path, method: :delete)

app/views/layouts/_icons.html.haml
= favicon_link_tag 'icons/car-16.png', rel: 'icon', type: 'image/png', sizes: '16x16'
= favicon_link_tag 'icons/car-32.png', rel: 'icon', type: 'image/png', sizes: '32x32'
= favicon_link_tag 'icons/car-48.png', rel: 'icon', type: 'image/png', sizes: '48x48'
= favicon_link_tag 'icons/car-64.png', rel: 'icon', type: 'image/png', sizes: '64x64'

= favicon_link_tag 'icons/car-57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57'
= favicon_link_tag 'icons/car-72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72'
= favicon_link_tag 'icons/car-114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114'
= favicon_link_tag 'icons/car-120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120'
= favicon_link_tag 'icons/car-144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144'
= favicon_link_tag 'icons/car-152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    = render 'layouts/icons'
    %title Motohelper
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ content: 'IE=edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }
  %body
    = render 'layouts/header'
    %main.container{ role: 'main' }
      = render 'layouts/flash_messages'
      = yield
    = render 'layouts/footer'